name: Check File Change

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-file-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check if file has been changed
        run: |
          if git diff --quiet HEAD~ HEAD jay.txt; then
            echo "File has not been changed in the pull request. Aborting workflow."
            exit 1
          else
            echo "File has been changed in the pull request. Continuing with next steps."
        # Add more steps here to continue with the workflow if the file has been changed.

