name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for changes in file
      id: file_changes
      run: |
        if git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep -q jay.txt; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
        fi
      shell: bash

    - name: Continue or Abort
      if: steps.file_changes.outputs.changed == 'true'
      run: echo "There is a change. Continuing next tasks."
    
    - name: Abort workflow
      if: steps.file_changes.outputs.changed != 'true'
      run: echo "There is no change. Aborting workflow."

