name: Pull Request Approved and File Changed

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check if file is changed
        id: file_changed
        run: echo ::set-output name=changed::$(git diff --name-only HEAD^ HEAD | grep 'dina.txt' || true)

      - name: Build and Test
        if: github.event.review.state == 'approved' && steps.file_changed.outputs.changed
        run: |
          # build and test commands go here
