name: Run action on approved pull request to main branch with one file change
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]

jobs:
  my-job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.changed_files == 1 && contains(github.event.pull_request.changed_files, 'jay.txt')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run your action
        run: your-action-command-here
