name: Run action on approved pull request to main branch with one file change
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  my-job:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.changed_files, 'jay.xlsv')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run your action
        run: your-action-command-here
