name: Pull Request Approve and File Change

on:
  pull_request:
    types: [review_requested, review_requested_removed, approved, edited, reopened]
    paths:
      - 'dina.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
