name: PR Approval with File Changes Check

on:
  pull_request_review:
    types: [approved]

jobs:
  pr-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check for file changes
        run: |
          if git diff --quiet ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- jay.txt
          then
            echo "change in the file, continuing workflow."
          else
            echo "No Changes found in file. aborting workflow."
            exit 1
          fi
      - name: Next steps
        run: |
          echo " hi jayapal"
