name: My Workflow

on:
  pull_request_review:
    types: [submitted]
    paths:
      - jayapal.xlsv

jobs:
  my-job:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Additional steps for the job
