name: Check File Change

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened]

jobs:
  check-file-change:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install PyGithub
        run: pip install PyGithub
      - name: Check if file has been changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          import os
          from github import Github

          # Get the repository and pull request objects
          g = Github(os.environ['GITHUB_TOKEN'])
          repo = g.get_repo('${{ github.repository }}')
          pr = repo.get_pull(${{ github.event.pull_request.number }})

          # Check if the pull request has been approved
          reviews = pr.get_reviews()
          approved = False
          for review in reviews:
              if review.state == 'APPROVED':
                  approved = True
                  break

          # If the pull request has been approved and the file has been changed, execute your code
          if approved:
              file_changed = False
              commits = pr.get_commits()
              for commit in commits:
                  files = commit.files
                  for file in files:
                      if file.filename == 'jat.txt':
                          file_changed = True
                          break
                  if file_changed:
                      break

              if file_changed:
                  # Execute your code here
                  echo 'The file has been changed.'
              else:
                  echo 'The file has not been changed.'
          else:
              echo 'The pull request has not been approved yet.'
      
