name: Run on Pull Request Approve and File Change

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run only on approved pull request and file change
      if: ${{ github.event.review.state == 'approved' && contains(github.event.pull_request.changed_files, 'example_file.txt') }}
      run: |
        # Your commands to run when the conditions are met
