name: example-action

on:
  pull_request_review:
    types: [submitted, edited]
  push:
    paths:
      - 'jay.xlsv'

jobs:
  example-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
    steps:
      - name: example-step
        run: echo "Hello, world!"
