name: Check File Change

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened]

jobs:
  check-file-change:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check if file has been changed
        run: |
          if git diff --quiet "$(git merge-base HEAD^ HEAD)" HEAD jay.txt; then
            echo "File has not been changed in the pull request."
          else
            echo "File has been changed in the pull request."
          fi
