# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

       # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          pwd
          ls -la

      # - name: Set up Python 3.9
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.9
          
      # - name: Install dependencies Including Ansible
      #   run: |
      #     python -m pip install --upgrade pip
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # - name: Running csvtoini playbook
      #   run: |
      #     ansible-playbook main.yml
          
#       - name: Running insight playbook
#         env:
#           SSH_KEY: ${{ secrets.SSH_KEY }}
#           SSH_USER: ec2-user
#           SSH_IP: 13.233.83.195
#         run: |
#           'echo "hi" > ssh_key'
#           scp -ri ssh_key . $SSH_USER@$SSH_IP:/home/ec2-user/
#           ssh -i ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}

      # - name: copy file via ssh key
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: 13.233.83.195
      #     username: ec2-user
      #     port: 22
      #     key: ${{ secrets.SSH_KEY }}
      #     source: "."
      #     target: "/home/ec2-user/git/"
      
      - name: write inventory to file
        env:
          SSH-KEY: ${{ secrets.SSH_KEY }}
        run: 'echo "$SSH-KEY" > ssh-key'
          
      - name: executing remote ssh commands using password
        uses: ./
        with:
          ssh-key: ssh-key
          user: ec2-user
          host: 3.110.176.123
      
