name: My Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for file changes
        run: |
          if [ -z "$(git diff --name-only HEAD^ HEAD -- jay.txt)" ]; then
            echo "No changes found in file. Aborting."
            exit 1
          else
            echo "Changes found in file. Continuing."
          fi
      - name: Run your action
        run: echo "working"
