name: Check PR File Changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for file changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep "jay.txt"; then
            echo "There are changes in the file. Continuing with next steps..."
          else
            echo "No changes found in the file. Aborting workflow."
            exit 1
          fi
      
      # Continue with your next steps here, e.g.
      - name: Build and test code
        run: |
          # your build and test commands here
