name: PR Approved Workflow

on:
  pull_request_target:
    types: [closed]
    branches:
      - main
    paths:
      - 'dina.txt'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run some command
        run: echo "Hello, world!"
