name: example-action

on:
  pull_request_review:
    types: [approved]
  push:
    paths:
      - 'jay.txt'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: example-step
        run: echo "Hello, world!"
