name: PR Approval Workflow

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.changed_files > 0 && contains(github.event.pull_request.changed_files, 'jay.txt')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Continue with next tasks
        run: echo "File has been changed, continuing with next tasks."
  
  abort-workflow:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.pull_request.changed_files == 0 || !contains(github.event.pull_request.changed_files, 'jay.txt'))
    steps:
      - name: Abort workflow
        run: exit 1
