name: Check for PR changes

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes
        run: |
          git fetch
          if git diff --quiet "$GITHUB_BASE_REF".."$GITHUB_HEAD_REF"; then
            echo "No changes in PR. Aborting workflow."
            exit 1
          else
            echo "Changes found in PR. Continuing workflow."
          fi
      - name: Next steps
        run: |
          echo " hi jayapal"
